name: Run Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install poetry
        run: |
          pip install poetry
      - name: Syncify Client
        run: |
          python scripts/syncronizer.py
      - name: Start Server
        run: |
          cd api
          poetry install --no-root
          poetry run uvicorn src.main:app &
          sleep 5
          cd ..
        env:
          DATABASE_TYPE: sqlite
          CONNECTION_URI: sqlite:///api.db
      - name: Run Tests
        run: |
          cd sdk
          poetry install
          poetry run coverage run -m pytest
          poetry run coverage xml coverage.xml
          cd ..
      - name: Code Coverage
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: sdk/coverage.xml
          badge: true
          format: markdown

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
      - name: Stop Server
        run: |
          kill $(jobs -p) || true

          

